############################################ NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
      name: socket_proxy
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.91.0/24
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
############################################# SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key
include:
  ########################################### SERVICES
  # CORE
  - compose/traefik.yml
  - compose/socket-proxy.yml
  - compose/portainer.yml
  - compose/dozzle.yml
  - compose/homepage.yml
  # MEDIA
  - compose/plex.yml
  - compose/stash.yml
  - compose/tautulli.yml
  # MONITORING
  - compose/uptime-kuma.yml
  # WEBSITE
  - compose/nginx.yml
  # SECURITY
  - compose/authelia.yml