services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - t2_proxy
      - socket_proxy
    ports:
      - "3000:3000"
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.rule=Host(`homepage.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.homepage.middlewares=chain-authelia@file"
      - "traefik.http.routers.homepage.middlewares=chain-basic-auth@file"
      # HTTP Services
      - "traefik.http.routers.homepage.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
