services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    networks:
      - t2_proxy
      - socket_proxy
    ports:
      - 8443:8443
    volumes:
      - /appdata/obsidian/vaults:/vaults
      - /appdata/obsidian/config:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.obsidian.entrypoints=websecure"
      - "traefik.http.routers.obsidian.rule=Host(`obsidian.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.obsidian.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.obsidian.service=obsidian-svc"
      - "traefik.http.services.obsidian-svc.loadbalancer.server.port=8443"