services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /appdata/obsidian/vaults:/vaults
      - /appdata/obsidian/config:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOCKER_MODS: linuxserver/mods:universal-git
      CUSTOM_PORT: "8080"
      CUSTOM_HTTPS_PORT: "8443" 
      CUSTOM_USER: ""
      PASSWORD: ""
      SUBFOLDER: ""