services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "all"]
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu] #the deploy section is the only way I've gotten it to use GPU transcoding
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp" # conflicts with xTeVe and Synology default ports
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400"
    #devices:
      #- /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $DOWNLOADSDIR/downloads:/data/downloads
      - /peterpool/media:/data/media
      #- /dev/shm:/transcode  #offload transcoding to RAM if you have enough
    environment:
      TZ: $TZ
      HOSTNAME: "PeachyPlex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_IP:32400/" ##"http://$SERVER_IP1:32400/,http://$SERVER_IP2:32400,https://splex.$DOMAINNAME_HS,https://splex.$DOMAINNAME_DS918,http://$ZEROTIER_IP_SYNOLOGY:32400/"
      ALLOWED_NETWORKS: $LOCAL_IPS
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    secrets:
      - plex_claim
    #labels:
     # - "traefik.enable=true"
      ## HTTP Routers
      #- "traefik.http.routers.plex-rtr.entrypoints=https"
      #- "traefik.http.routers.plex-rtr.rule=Host(`PeachyPlex.$DOMAINNAME_1`)"
      ## Middlewares
      #- "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      #- "traefik.http.routers.plex-rtr.service=plex-svc"
      #- "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
